src/modules/DecksList/components/DecksList.tsx, src/modules/DecksList/index.ts, src/navigation/index.tsx, src/navigation/interface.ts
=> Fix require cycle

src/common/Alert.tsx, src/common/index.ts, src/redux/actions.ts, src/redux/interface.ts, src/redux/reducer.ts, src/screens/DeckDetail/components/Cards.tsx, src/screens/DeckDetail/index.tsx
=> delete specific card

src/common/AlertModal.tsx, src/common/CloseButton.tsx, src/common/IconButton.tsx, src/common/index.ts, src/navigation/index.tsx, src/navigation/interface.ts, src/screens/AnswerModal.tsx, src/screens/DeckDetail/index.tsx, src/screens/Playground/Card.tsx, src/screens/Playground/Carousel.tsx, src/screens/Playground/index.tsx, src/screens/QuestionModal.tsx
#25, #26
TODO:
#16 - I think this will resolve the dilemma about #26
=> open specific modal from card, scrollToItem on playground flatlist

src/utils/index.ts, src/utils/shuffleArray.ts
=> adds shuffle function

src/common/Button.tsx, src/common/Container.tsx, src/common/index.ts, src/navigation/DrawerNavigator.tsx, src/navigation/DrawerStack.tsx, src/navigation/index.tsx, src/navigation/interface.ts, src/screens/RateTheApp.tsx, src/screens/SettingsDrawerContent.tsx, src/styles/colors.ts
=> adds rate us screen, get freebie screens to drawer

README.md, android/app/build.gradle, android/app/src/main/java/com/flashcards/MainApplication.java, android/app/src/main/java/com/flashcards/modules/FlashCardsRateAppModule.java, android/app/src/main/java/com/flashcards/modules/FlashCardsRateAppPackage.java, ios/FlashCards.xcodeproj/project.pbxproj, ios/Modules/FlashCardsRateApp.h, ios/Modules/FlashCardsRateApp.m, src/modules/RateApp.tsx, src/modules/rateApp.tsx, src/screens/RateTheApp.tsx
=> rate the app in IOS and Android

package.json, src/common/Form.tsx, src/screens/DeckDetail/components/Cards.tsx, yarn.lock
=> upgrafe rich editor to 1.6.3

src/common/AddButton.tsx, src/common/IconButton.tsx, src/hooks/useAnimatedPress.ts, src/navigation/DrawerNavigator.tsx, src/screens/Home/AddDeck.tsx, src/screens/Home/DecksList/DeckItem.tsx, src/screens/Home/DecksList/index.tsx, src/utils/theme.ts
- animate decks list
- on press icon button animation
=> Animated home list

.gitignore, ios/Podfile.lock, package.json, src/api/index.ts, yarn.lock
=> adds config IOS

.gitignore, README.md, appcenter-key.sh, appcenter-pre-build.sh, ios/AppCenter-Config.plist, ios/Config.xcconfig, ios/FlashCards.xcodeproj/project.pbxproj, ios/FlashCards.xcodeproj/xcshareddata/xcschemes/FlashCards.xcscheme, ios/FlashCards/AppDelegate.m, ios/FlashCards/Info.plist, ios/Podfile.lock, package.json, src/redux/reducer.ts, yarn.lock
=> feat: create script to read app center key from env file

src/api/index.ts, src/common/NoContentInfo.tsx, src/common/TopBar.tsx, src/common/index.ts, src/screens/Home/DecksList/index.tsx
=> fix: few issues

src/redux/reducer.ts, src/screens/Home/AddDeck.tsx, src/screens/Home/DecksList/index.tsx
=> feat: add new deck to the top of the object, close AddDeck 

src/common/AlertModal.tsx
=> feat: replace text with input for share code

src/common/AlertModal.tsx, src/screens/DeckDetail/components/CardItem.tsx, src/screens/DeckDetail/components/Cards.tsx, src/screens/Home/AddDeck.tsx
=> adds trash icon to the card item component

src/App.tsx, src/common/AlertModal.tsx, src/modules/rateApp.tsx, src/navigation/index.tsx, src/screens/Drawer/ShareTheApp.tsx, src/utils/analytics.ts, src/utils/index.ts
=> adds analytics events

src/App.tsx, src/common/AlertModal.tsx, src/common/Form.tsx, src/modules/rateApp.tsx, src/screens/Drawer/Contact.tsx, src/screens/Drawer/GetFreebie.tsx, src/utils/analytics.ts
Analytics: 
remove setEnabled - potentially not needed - test in prod
=> remove potentially not needed code for analytics

android/app/src/main/java/com/flashcards/MainApplication.java, android/app/src/main/java/com/flashcards/modules/FlashCardsAppVersionModule.java, android/app/src/main/java/com/flashcards/modules/FlashCardsAppVersionPackage.java, ios/FlashCards.xcodeproj/project.pbxproj, ios/Modules/FlashCardsAppVersion.h, ios/Modules/FlashCardsAppVersion.m, src/modules/AppVersion.tsx, src/screens/Drawer/DrawerContent.tsx
=> feat: adds AppVersion Native module

src/redux/decks/reducer.ts, src/redux/decks/sagas/getDeckByShareIdSaga.ts, src/screens/AnswerModal.tsx, src/screens/DeckDetail/components/CardItem.tsx, src/screens/DeckDetail/components/Cards.tsx, src/screens/DeckDetail/index.tsx, src/screens/Playground/index.tsx, src/screens/QuestionModal.tsx
=> fix: delete card and sharing functioanlity

src/components/Modals/CodeContentModal.tsx, src/redux/decks/actions.ts, src/redux/decks/interface.ts, src/redux/decks/reducer.ts, src/redux/decks/sagas/getDeckByShareIdSaga.ts, src/screens/DeckDetail/index.tsx, src/screens/QuestionModal.tsx
=> fix editing shared deck

src/common/GeneralAlert.tsx, src/common/index.ts, src/components/Modals/CodeContentModal.tsx, src/navigation/types.ts, src/redux/decks/actions.ts, src/redux/decks/interface.ts, src/redux/decks/reducer.ts, src/redux/decks/sagas/clearErrorSaga.ts, src/redux/decks/sagas/editDeckBySharedIdSaga.ts, src/redux/decks/sagas/getDeckByShareIdSaga.ts, src/redux/rootSaga.ts, src/screens/Home/AddDeck/index.tsx, src/utils/theme.ts
=> adds error notification on adding shared deck

src/assets/animations/index.ts, src/common/Form.tsx, src/common/HtmlParser.tsx, src/common/ProgressLoader.tsx, src/common/index.ts, src/lib/getUserScore.ts, src/lib/index.ts, src/screens/DeckDetail/components/CardItem.tsx, src/screens/DeckDetail/components/Cards.tsx, src/screens/Playground/NoMoreCards.tsx
#99, #153 
Improve cards height - WIP
=> Issue 153/loading image

src/common/Form.tsx, src/common/GeneralAlert/index.tsx, src/common/HtmlParser.tsx, src/screens/DeckDetail/components/CardItem.tsx, src/screens/DeckDetail/index.tsx, src/screens/Drawer/Shop/Content.tsx, src/screens/Drawer/UpgradeToPro/Content.tsx, src/utils/device.ts, src/utils/theme.ts, src/utils/useIsMount.ts
FIx Image height in Cards
Fix Alert rendering issues and height on iphone with notch
=> fix image height and alert

README.md, android/app/build.gradle, android/sentry.properties, appcenter-pre-build.sh, ios/FlashCards.xcodeproj/project.pbxproj, ios/Podfile.lock, ios/sentry.properties, package.json, sentry-keys.sh, src/App.tsx, src/common/GeneralAlert/index.tsx, src/components/Modals/ShareContentModal.tsx, src/modules/rateApp.tsx, src/modules/usePayments.ts, src/screens/Drawer/Contact.tsx, src/screens/Drawer/RequestFeature.tsx, src/screens/Home/DecksList/index.tsx, src/service/Logger.ts, src/service/useInterstitialAd.ts, yarn.lock
=> feat: adds sentry logger

src/screens/Home/AddDeck/index.tsx
=> fix: shop flow from add deck screen

src/common/AnimatedView.tsx, src/common/Container.tsx, src/screens/DeckDetail/components/Menu.tsx, src/screens/DeckDetail/components/TransitionedCards.tsx, src/screens/DeckDetail/index.tsx, src/utils/device.ts
=> fix menu button not clickable on android

src/api/index.ts, src/api/types.d.ts, src/common/Bubble.tsx, src/redux/decks/sagas/getDeckByShareIdSaga.ts
=> fix: persist rank

.gitignore, ios/FlashCards.xcodeproj/project.pbxproj, ios/Podfile.lock, package.json, src/api/index.ts, src/redux/decks/reducer.ts, src/redux/decks/sagas/getDeckByShareIdSaga.ts, yarn.lock
#233
Needs PR in backend to be merged first: https://github.com/heron2014/flashcards-api/pull/37
I also updated Sentry and added a bit of script to allow to run the app when using nvm.
=> fix offline cards disapearing when going back online on shared decks

src/api/index.ts, src/redux/decks/sagas/getDeckByShareIdSaga.ts, src/screens/DeckDetail/index.tsx, src/screens/DeckDetail/useDeckPusher.tsx, src/screens/LoginOrSignup/components/Input.tsx
Requires: https://github.com/heron2014/flashcards-api/pull/46
=> fix get shared card by id broken
